const defaultTheme = {
    ltr: "ltr",
    rtl: "rtl",
    placeholder: "editor-placeholder",
    paragraph: "richtext-paragraph",
    quote: "richtext-quote",
    heading: {
        h1: "richtext-heading-h1",
        h2: "richtext-heading-h2",
        h3: "richtext-heading-h3",
        h4: "richtext-heading-h4",
        h5: "richtext-heading-h5",
    },
    list: {
        nested: {
            listitem: "richtext-nested-listitem",
        },
        ol: "richtext-list-ol",
        ul: "richtext-list-ul",
        listitem: "richtext-listitem",
    },
    image: "richtext-image",
    link: "richtext-link",
    text: {
        bold: "richtext-text-bold",
        italic: "richtext-text-italic",
        overflowed: "richtext-text-overflowed",
        hashtag: "richtext-text-hashtag",
        underline: "richtext-text-underline",
        strikethrough: "richtext-text-strikethrough",
        underlineStrikethrough: "richtext-text-underlineStrikethrough",
        code: "richtext-text-code",
    },
    code: "richtext-code",
    codeHighlight: {
        atrule: "richtext-tokenAttr",
        attr: "richtext-tokenAttr",
        boolean: "richtext-tokenProperty",
        builtin: "richtext-tokenSelector",
        cdata: "richtext-tokenComment",
        char: "richtext-tokenSelector",
        class: "richtext-tokenFunction",
        "class-name": "richtext-tokenFunction",
        comment: "richtext-tokenComment",
        constant: "richtext-tokenProperty",
        deleted: "richtext-tokenProperty",
        doctype: "richtext-tokenComment",
        entity: "richtext-tokenOperator",
        function: "richtext-tokenFunction",
        important: "richtext-tokenVariable",
        inserted: "richtext-tokenSelector",
        keyword: "richtext-tokenAttr",
        namespace: "richtext-tokenVariable",
        number: "richtext-tokenProperty",
        operator: "richtext-tokenOperator",
        prolog: "richtext-tokenComment",
        property: "richtext-tokenProperty",
        punctuation: "richtext-tokenPunctuation",
        regex: "richtext-tokenVariable",
        selector: "richtext-tokenSelector",
        string: "richtext-tokenSelector",
        symbol: "richtext-tokenProperty",
        tag: "richtext-tokenProperty",
        url: "richtext-tokenOperator",
        variable: "richtext-tokenVariable",
    },
};

export default defaultTheme;
